---
title: "القسمة في مجموعة الأعداد الصحيحة ℤ"
format:
  html:
    lang: ar
    toc: true
    number-sections: true
    css: styles.css
    html-math-method: mathjax
editor: visual
---

في كل مايلي نعتبر$ $a$، $b$، $c$ أعداد صحيحة غير معدومة. $n$ عدد طبيعي غير معدوم

::: {.callout-note title="تعريف"}

نقول إن $a$ يقسم $b$ (أو أن $b$ مضاعف لـ $a$) **إذا وفقط إذا** وُجد عدد صحيح $k$ بحيث:

$$
b = a \cdot k.
$$

ونكتب ذلك على الشكل:
$a \mid b$.
 
:::

::: callout-tip
### مثال

1.  $7\mid 938$ لأن $938=7 \times 134$
2.  $n+2\mid 3n^3+7n^2-2n-8$ لأن $3 n^3+7n^2-2n-8=(n+2) (3n^2+n-4)$
3.  $\forall n\in \{-11,-6,-3,-2,-1,0,1,4\}$ : $n+1\mid 3n+13$ لأن  $$
    \frac{3n+13}{n+1}
    = 3 + \frac{10}{n+1}.
    $$ إن
    حتى يكون العدد
    $\frac{3n+13}{n+1}$ عددًا صحيحًا، يجب أن يكون:

$$
n+1 \mid 10
$$
:::

::: callout-note
### ملاحظة

1.  في $\mathbb{Z}$ للعددين $a$ و $-a$ نفس القواسم الصحيحة.
2.  العددان $1$ و $-1$ يقسمان أي عدد صحيح $a$ أي: $1 \mid a$ و $-1 \mid a$.
3.  كل عدد صحيح غير معدوم $a$ يختلف عن $1$ و $-1$ يقبل على الأقل أربعة قواسم وهي: $$
    1,\ -1,\ a,\ -a.
    $$
:::

## خواص قابلية القسمة في $\mathbb{Z}$

1.  إذا كان $a \mid b$ و $b \mid c$ فإن: $$
    a \mid c
    $$

2.  إذا كان $a \mid b$ فإن: $$
    a \mid mb
    $$

3.  إذا كان $a \mid b$ فإن: $$
    ma \mid mb
    $$

4.  إذا كان $a \mid b$ و $a \mid c$ فإنه من أجل كل عددين صحيحين $\alpha,\beta$: $$
    a \mid (\alpha b + \beta c)
    $$

<h2>البرهان</h2> 
1.  لدينا $b = ak$ و $c = b\ell$ من أجل عددين صحيحين $k$ و $\ell$ ينتميان إلى $\mathbb{Z}$.

إذن:

$$
c = b\ell = a(k\ell).
$$

وبما أن $k\ell \in \mathbb{Z}$ فإن:

$$
a \mid c.
$$ 2. لدينا $b = ak$ من أجل عدد صحيح $k \in \mathbb{Z}$.

إذن:

$$
bc = (ak)c = a(kc).
$$

وبما أن $kc \in \mathbb{Z}$ فإن:

$$
a \mid bc.
$$

3.  بنفس الطريقة أعلاه
4.  لدينا $b = ak$و $c = a\ell$ من أجل $k,\ell \in \mathbb{Z}$.

إذن:

$$
\alpha b + \beta c = \alpha ak + \beta a\ell = a(\alpha k + \beta \ell).
$$

وبما أن $\alpha k + \beta \ell \in \mathbb{Z}$ فإن:

$$
a \mid (\alpha b + \beta c).
$$

::: callout-tip
### مثال

برهن أنه اذا كان $d$ عدد صحيح غير معدوم يحقق

$$
d\mid 6n+2
\quad \text{و} \quad
d\mid 4n+11
$$

فإن

$$
d\mid 29.
$$ الحل

نبحث عن عددين صحيحين $\alpha$ و $\beta$ بحيث:

$$
\alpha(6n+2) + \beta(4n+11) = 29....(1)
$$

ومنه:

$$
\alpha(6n+2) + \beta(4n+11)
= (6\alpha + 4\beta)n + (2\alpha + 11\beta)....(2) 
$$

بالمطابقة (1)و( 2)

$$
6\alpha + 4\beta = 0 
\quad \text{و} \quad
2\alpha + 11\beta = 29 
$$

نجد $\alpha=2$ و $\beta=-3$
:::

## القسمة الإقليدية

::: {.callout-note title="تعريف"}
توجد ثنائية وحيدة $(q,r)$ من $\mathbb{Z}\times\mathbb{N}$ تحقق: $$
a = bq + r
$$

حيث: $0 \le r < |b|$

أو بعبارة اخرى $$
\forall (a,b)\in \mathbb{Z}\times \mathbb{Z}^* \;\; \exists !(q,r)\in \mathbb{Z}\times \mathbb{N} \;:\; a=bq+r
$$

$$
0 \le r < |b|.
$$
:::

::: callout-tip
### مثال

عيّن باقي القسمة الإقليدية للعدد $7n+41$ على $n+5$ .

الحل

لدينا:

$$
7n+41 = 7(n+5) + 6. 
$$

إذن باقي القسمة هو $6$ إذا تحقق:

$$
0 \le 6 < n+5 \quad \Longleftrightarrow \quad n>1. 
$$

إذن:

-   إذا كان $n>1$ فإن باقي القسمة الإقليدية هو $\boxed{6}$.

تبقى الحالات $n=0,1$:

-   إذا كان $n=1$ فإن $7n+41=48$ و $n+5=6$، وبالتالي الباقي هو $0$.
-   إذا كان $n=0$ فإن $7n+41=41$ و $n+5=5$، وبالتالي الباقي هو $1$.
:::

## القاسم المشترك الأكبر لعددين طبيعيين

::: {.callout-note title="تعريف"}
ليكن $a$ و $b$ عددين طبيعيين غير معدومين.

نرمز بـ $D_a$ مجموعة قواسم $a$، وبـ $D_b$ مجموعة قواسم $b$.

تسمى مجموعة القواسم المشتركة للعددين $a$ و $b$ بالمجموعة:

$$
D_a \cap D_b.
$$

أكبر عنصر في هذه المجموعة يسمى **القاسم المشترك الأكبر** للعددين $a$ و $b$، ويرمز إليه بـ:

$$
PGCD(a,b).
$$

وبالتالي:

$$
PGCD(a,b) = \max\bigl(D_a \cap D_b\bigr).
$$
:::

### كيف نجد عدد و مجموعة قواسم عدد طبيعي $a$؟

::: {.callout-important title="طريقة"}
**
نحلل العدد$ a$ إلى جداء عوامله الأولية.

إذا كان:

$$
a = p^{\alpha}\, q^{\beta}\, r^{\gamma}\, \cdots
$$

حيث $p,q,r,\ldots$ أعداد أولية و $\alpha,\beta,\gamma,\ldots$ أعداد طبيعية، فإن **عدد قواسم** $a$ هو:

$$
(\alpha+1)(\beta+1)(\gamma+1)\cdots
$$
** نستعمل شجرة الحلات المختلفة

:::

::: callout-tip
### مثال
أوجد جميع القواسم الطبيعية للعدد $75$.

لدينا:

$$
75 = 3 \times 5^2.
$$

اذن عدد قواسم العدد
$75$
هو 23

| $3^i$ | $5^j$ | القاسم $3^i \times 5^j$ | 
|---:|---:|---:|
| $3^0$ | $5^0$ | $1$ |
| $3^0$ | $5^1$ | $5$ |
| $3^0$ | $5^2$ | $25$ |
| $3^1$ | $5^0$ | $3$ |
| $3^1$ | $5^1$ | $15$ |
| $3^1$ | $5^2$ | $75$ |
:::

## خصائص القاسم المشترك الأكبر $PGCD$
$a,b$ عددين طبيعيين غير معدومين

1.
   $$
   PGCD(a,a)=a,\qquad PGCD(a,0)=a,\qquad PGCD(a,1)=1.
   $$

2.
   $$
   D_a \cap D_b = D_{PGCD(a,b)}.
   $$

3. إذا كان $a,b$ عددين 
طبيعيين غير معدومين حيث $a \ge b$ و $r$ باقي قسمة $a$ على $b$، فإن:
   $$
   PGCD(a,b)=PGCD(b,r).
   $$

4. $k$ عددًا طبيعيًا غير معدوم، فإن:
   $$
   PGCD(ka,kb)=k\,PGCD(a,b).
   $$

::: {.callout-note title="مساواة باشيه–بيزو"}

ليكن $d = PGCD(a,b)$.

يوجد عددان صحيحان $u$ و $v$ بحيث:

$$
au + bv = d.
$$
:::

تعطي مبرهنة بيزو عكس هذه الخاصية عندما يكون $d = 1$، أي عندما يكون العددان **أوليين فيما بينهما**.

::: {.callout-note title="مبرهنة بيزو"}
العددان الصحيحان $a$ و $b$ أوليان فيما بينهما **إذا وفقط إذا** وُجد عددان صحيحان $u$ و $v$ بحيث:

$$
au + bv = 1.
$$
:::


::: {.callout-note title="مبرهنة غوص"}
إذا كان $a \mid bc$ وكان $a$ اوليًا مع$b$، فإن:

$$
a \mid c.
$$
:::

## الموافقات في $\mathbb{Z}$
::: {.callout-note title="تعريف"}

نقول إن $a$ و $b$ **متوافقان بترديد $n$** إذا كان لهما نفس باقي  القسمة الإقليدية على $n$. 
ونكتب:

$$
a \equiv b \ [n].
$$

كما نقول إن: $a$ يوافق $b$ بترديد $n$.
:::

---



::: {.callout-note title="مبرهنة "}
إن $a$ و $b$ لهما نفس باقي القسمة الإقليدية على $n$ **إذا وفقط إذا** كان:

$$
n \mid (a-b)
\Longleftrightarrow \exists k\in\mathbb{Z} : a-b = nk
\Longleftrightarrow a-b \equiv 0 \ [n].
$$

:::

---
## خواص الموافقة

في كل ما يلي نعتبر $n,\alpha$ أعدادًا طبيعية غير معدومة 

1. $a \equiv a \ [n]$.

2. إذا كان $a \equiv b \ [n]$ فإن $b \equiv a \ [n]$.

3. إذا كان:
   $$
   \begin{cases}
   a \equiv b \ [n] \\
   b \equiv c \ [n]
   \end{cases}
   $$
   فإن:
   $$
   a \equiv c \ [n].
   $$

4. إذا كان:
   $$
   \begin{cases}
   a \equiv b \ [n] \\
   c \equiv d \ [n]
   \end{cases}
   $$
   فإن:
   $$
   \begin{cases}
   a+c \equiv b+d \ [n] \\
   a\times c \equiv b\times d \ [n]
   \end{cases}
   $$

5. إذا كان $a \equiv b \ [n]$ فإن:
   $$
   \alpha a \equiv \alpha b \ [\alpha n].
   $$

6. إذا كان $a \equiv b \ [n]$ فإن:
   $$
   a^{\alpha} \equiv b^{\alpha} \ [n].
   $$

7. إذا كان $a \equiv b \ [n]$ فإن:
   $$
   ka \equiv kb \ [n].
   $$
   <h2>البرهان</h2> 
   
1.نعلم أن كل عدد طبيعي غير معدوم يقسم $0$، أي:
$n \mid 0$ و $a-a=0$.

إذن:

$$
n \mid (a-a).
$$

وبالتالي حسب تعريف الموافقة:

$$
a \equiv a \ [n].
$$

2.إذا كان $a \equiv b \ [n]$ فهذا يعني حسب تعريف الموافقة أن:

$$
n \mid (a-b).
$$

أي يوجد عدد صحيح $k$ بحيث:

$$
a-b = nk.
$$
نستنتج:

$$
b = a - nk.
$$

وبما أن $-k \in \mathbb{Z}$ نضع $k'=-k$  نجد:

$$
b = a + nk'.
$$

إذن:

$$
b-a = nk' \quad \Rightarrow \quad n \mid (b-a) \quad \Rightarrow \quad b \equiv a \ [n].
$$

بنفس الطريقة يمكن البرهان على الخاصية 3-4-5-7.

6.  
 لدينا $a \equiv b \ [n]$.

**1) لما $\alpha=1$ نحصل على:

$$
a^1=a \equiv b=b^1 \ [n].
$$

**2) نفرض أن

$$
a^{\alpha} \equiv b^{\alpha} \ [n].
$$

**3) 

$$
a \equiv b \ [n]
\quad \text{و} \quad
a^{\alpha} \equiv b^{\alpha} \ [n],
$$

باستعمال خاصية الجداء نحصل على

$$
a \cdot a^{\alpha} \equiv b \cdot b^{\alpha} \ [n].
$$

أي:

$$
a^{\alpha+1} \equiv b^{\alpha+1} \ [n].
$$

إذن حسب مبدأ التراجع:

$$
\forall \alpha \in \mathbb{N}^*, \quad a^{\alpha} \equiv b^{\alpha} \ [n].
$$

::: {.callout-note title="مبرهنة فيرما الصغرى"}
ليكن $p$ عددًا أوليًا موجبًا
فان
$$
a^p \equiv a \ [p]. 
$$


:::